Fix ConvTranspose.call argument order by passing keywords
ConvTranspose.call previously passed self.output_padding as the 4th
positional argument (which is padding in conv_transpose) and self.padding
as the 5th positional argument (which is output_padding). This caused
Functional models calling keras.ops.conv_transpose to fail with
AttributeError: 'NoneType' object has no attribute 'lower'.

Pass all arguments after kernel as keyword arguments to eliminate any
positional ordering mismatch. Add a Functional model regression test with
output_padding.

Part of #23755