Import fails in Windows service because of stderr
There are no stderr and stdout in Windows service, so any attempt to write to it fails:
```
    sys.stderr.write('Using TensorFlow backend.\n')
AttributeError: 'NoneType' object has no attribute 'write' 
```
So in my opinion the library must be more careful when printing unavoidable messages.