merge master (#20741)
* Specify window_length dtype requirement in tf.keras.ops.istft in math.py (#20728)

The `window_length` parameter in `tf.keras.ops.istft` requires `tf.int32` dtype, but this isn't documented. This can cause unexpected `ValueError` when using `tf.int64` and `tf.int16`

Here is the Example case:
```
import tensorflow as tf

input_dict = {
    'stfts': tf.constant([[-0.87817144+1.14583987j, -0.32066484+0.25565411j]], dtype=tf.complex128),
    'frame_length': tf.constant(256, dtype=tf.int16),
    'frame_step': tf.constant(5120,dtype=tf.int64)
}
result = tf.signal.inverse_stft(**input_dict)
print(result)
```
The code throws the following error:
```
ValueError: window_length: Tensor conversion requested dtype int32 for Tensor with dtype int64
```

* Add rand_augment processing layer (#20716)

* Add rand_augment init

* Update rand_augment init

* Add rand_augment

* Add NotImplementedError

* Add some test cases

* Fix failed test case

* Update rand_augment

* Update rand_augment test

* Fix random_rotation bug

* Add build method to supress warning.

* Add implementation for transform_bboxes

* Fixing batch_dim_name attribute (#20674)

* fixing wrong trainer assumption that batch dim is always the first one in the mesh

* need functools partial

* lint

* fix test failure when distribution=None

* lint2

* fix for test failure

* added data sharding for 3D+ meshes

* lint3

* added @property for batch_dim_name + refactoring

* fix typo

* Add support for `dtype` / `DTypePolicy` to `JaxLayer` and `FlaxLayer`. (#20732)

The `dtype` / `DTypePolicy` is applied to all float variables.

* Allow dynamic shape in `STFTSpectrogram` layer. (#20736)

by simply using `ops.shape(x)` instead of `x.shape`.

* Remove duplicate export tests in `model_test`. (#20735)

The same tests exist at:
- https://github.com/keras-team/keras/blob/master/keras/src/export/saved_model_test.py#L66
- https://github.com/keras-team/keras/blob/master/keras/src/export/onnx_test.py#L62

The goal is to isolate the use of `onnxruntime` to a single file, `onnx_test.py`.

* Add OpenVINO into README.md (#20739)

* Add OpenVINO into README.md

Signed-off-by: Kazantsev, Roman <roman.kazantsev@intel.com>

* Update README.md

---------

Signed-off-by: Kazantsev, Roman <roman.kazantsev@intel.com>

* Multiple Example Title has removed in metrics.MeanIoU method (#20738)

Multiple Example Title has removed in metrics.MeanIoU method

---------

Signed-off-by: Kazantsev, Roman <roman.kazantsev@intel.com>
Co-authored-by: LakshmiKalaKadali <149650845+LakshmiKalaKadali@users.noreply.github.com>
Co-authored-by: Ugeun Park <37043543+shashaka@users.noreply.github.com>
Co-authored-by: Martin Görner <martin-gorner@users.noreply.github.com>
Co-authored-by: hertschuh <1091026+hertschuh@users.noreply.github.com>
Co-authored-by: Roman Kazantsev <roman.kazantsev@intel.com>
Co-authored-by: LavanyaKV1234 <154420106+LavanyaKV1234@users.noreply.github.com>