Updated the source code for Multilayer Perceptron (MLP) multi-class classification
The code given would result in a NameError over missing parentheses.
NameError: name 'sgd' is not defined